from __future__ import annotations

import re
from decimal import Decimal

from prometheus_client import CONTENT_TYPE_LATEST as PROMETHEUS_CONTENT_TYPE_LATEST
from prometheus_client import CollectorRegistry, Counter, Gauge, Histogram, generate_latest

CONTENT_TYPE_LATEST = PROMETHEUS_CONTENT_TYPE_LATEST


REGISTRY = CollectorRegistry(auto_describe=True)

_DYNAMIC_SEGMENT_RE = re.compile(r"/(?:\d+|[0-9a-fA-F]{8,}(?:-[0-9a-fA-F]{4,})*)")
_SAFE_LABEL_RE = re.compile(r"[^a-zA-Z0-9_.:/{}-]")


HTTP_REQUESTS = Counter(
    "interview_agent_http_requests",
    "HTTP requests by method, normalized route and status class.",
    ("method", "route", "status_class"),
    registry=REGISTRY,
)
HTTP_REQUEST_DURATION = Histogram(
    "interview_agent_http_request_duration_seconds",
    "HTTP request duration in seconds by method and normalized route.",
    ("method", "route"),
    registry=REGISTRY,
)
HTTP_EXCEPTIONS = Counter(
    "interview_agent_http_exceptions",
    "HTTP 4xx/5xx responses by normalized route and status class.",
    ("route", "status_class"),
    registry=REGISTRY,
)

SESSIONS_CREATED = Counter(
    "interview_agent_sessions_created",
    "Sessions created by mode.",
    ("mode",),
    registry=REGISTRY,
)
ANSWERS_SUBMITTED = Counter(
    "interview_agent_answers_submitted",
    "Answers submitted by session mode.",
    ("mode",),
    registry=REGISTRY,
)
REPORTS_GENERATED = Counter(
    "interview_agent_reports_generated",
    "Reports generated by status.",
    ("status",),
    registry=REGISTRY,
)
MEMORIES_CREATED = Counter(
    "interview_agent_memories_created",
    "Agent memories created by low-cardinality memory type.",
    ("memory_type",),
    registry=REGISTRY,
)
MEMORY_REFRESH = Counter(
    "interview_agent_memory_refresh",
    "Agent memory refresh attempts by status and trigger.",
    ("status", "trigger"),
    registry=REGISTRY,
)
ASYNC_JOBS_CREATED = Counter(
    "interview_agent_async_jobs_created",
    "Async jobs created by job type.",
    ("job_type",),
    registry=REGISTRY,
)
ASYNC_JOBS_COMPLETED = Counter(
    "interview_agent_async_jobs_completed",
    "Async jobs completed by job type and terminal status.",
    ("job_type", "status"),
    registry=REGISTRY,
)
ASYNC_JOB_DURATION = Histogram(
    "interview_agent_async_job_duration_seconds",
    "Async job execution duration by job type.",
    ("job_type",),
    registry=REGISTRY,
)
ASYNC_JOBS_IN_PROGRESS = Gauge(
    "interview_agent_async_jobs_in_progress",
    "Async jobs currently running by job type.",
    ("job_type",),
    registry=REGISTRY,
)
RATE_LIMIT_EXCEEDED = Counter(
    "interview_agent_rate_limit_exceeded",
    "Rate limit denials by low-cardinality scope.",
    ("scope",),
    registry=REGISTRY,
)
QUOTA_EXCEEDED = Counter(
    "interview_agent_quota_exceeded",
    "Quota denials by low-cardinality quota type.",
    ("quota_type",),
    registry=REGISTRY,
)
DATA_EXPORTS = Counter(
    "interview_agent_data_exports",
    "Current-user data export attempts by status.",
    ("status",),
    registry=REGISTRY,
)
DATA_DELETIONS = Counter(
    "interview_agent_data_deletions",
    "Current-user data deletion attempts by status and low-cardinality scope.",
    ("status", "scope"),
    registry=REGISTRY,
)

LLM_CALLS = Counter(
    "interview_agent_llm_calls",
    "LLM calls by provider, model, feature and status.",
    ("provider", "model", "feature", "status"),
    registry=REGISTRY,
)
LLM_TOKENS = Counter(
    "interview_agent_llm_tokens",
    "LLM token counts by provider, model, feature and token type.",
    ("provider", "model", "feature", "token_type"),
    registry=REGISTRY,
)
LLM_ESTIMATED_COST = Counter(
    "interview_agent_llm_estimated_cost",
    "Estimated LLM cost by provider, model, feature and currency.",
    ("provider", "model", "feature", "currency"),
    registry=REGISTRY,
)
LLM_LATENCY = Histogram(
    "interview_agent_llm_latency_seconds",
    "LLM call latency by provider, model and feature.",
    ("provider", "model", "feature"),
    registry=REGISTRY,
)

DEPENDENCY_READY = Gauge(
    "interview_agent_dependency_ready",
    "Dependency readiness status, 1 for ready and 0 for not ready.",
    ("dependency",),
    registry=REGISTRY,
)


def safe_label(value: object, default: str = "unknown") -> str:
    text = str(value or default).strip().lower()
    if not text:
        text = default
    text = _SAFE_LABEL_RE.sub("_", text)
    return text[:80] or default


def normalize_route(path: str | None) -> str:
    if not path:
        return "unknown"
    normalized = _DYNAMIC_SEGMENT_RE.sub("/{id}", path)
    return normalized[:120]


def status_class(status_code: int | None) -> str:
    if status_code is None:
        return "unknown"
    return f"{int(status_code) // 100}xx"


def record_http_request(method: str, route: str, status_code: int, duration_seconds: float) -> None:
    normalized_method = _SAFE_LABEL_RE.sub("_", str(method or "unknown").strip().upper())[:16] or "UNKNOWN"
    normalized_route = normalize_route(route)
    normalized_status_class = status_class(status_code)
    HTTP_REQUESTS.labels(normalized_method, normalized_route, normalized_status_class).inc()
    HTTP_REQUEST_DURATION.labels(normalized_method, normalized_route).observe(max(duration_seconds, 0.0))
    if status_code >= 400:
        HTTP_EXCEPTIONS.labels(normalized_route, normalized_status_class).inc()


def normalize_rate_limit_scope(scope: str) -> str:
    mapping = {
        "auth_ip_per_minute": "login_ip",
        "auth_phone_per_hour": "login_phone",
        "answer_submit_per_minute": "answer_submit",
    }
    return mapping.get(scope, safe_label(scope))


def normalize_quota_type(quota_name: str) -> str:
    mapping = {
        "llm_daily_token_quota": "daily_tokens",
        "llm_monthly_token_quota": "monthly_tokens",
        "llm_daily_call_quota": "daily_calls",
    }
    return mapping.get(quota_name, safe_label(quota_name))


def record_rate_limit_exceeded(scope: str) -> None:
    RATE_LIMIT_EXCEEDED.labels(normalize_rate_limit_scope(scope)).inc()


def record_quota_exceeded(quota_name: str) -> None:
    QUOTA_EXCEEDED.labels(normalize_quota_type(quota_name)).inc()


def record_data_export(status: str) -> None:
    DATA_EXPORTS.labels(safe_label(status)).inc()


def record_data_deletion(status: str, scope: str = "training_data") -> None:
    DATA_DELETIONS.labels(safe_label(status), safe_label(scope)).inc()


def record_session_created(mode: str) -> None:
    SESSIONS_CREATED.labels(safe_label(mode)).inc()


def record_answer_submitted(mode: str | None) -> None:
    ANSWERS_SUBMITTED.labels(safe_label(mode)).inc()


def record_report_generated(status: str) -> None:
    REPORTS_GENERATED.labels(safe_label(status)).inc()


def record_memory_created(memory_type: str) -> None:
    MEMORIES_CREATED.labels(safe_label(memory_type)).inc()


def record_memory_refresh(status: str, trigger: str) -> None:
    MEMORY_REFRESH.labels(safe_label(status), safe_label(trigger)).inc()


def record_async_job_created(job_type: str) -> None:
    ASYNC_JOBS_CREATED.labels(safe_label(job_type)).inc()


def record_async_job_completed(job_type: str, status: str) -> None:
    ASYNC_JOBS_COMPLETED.labels(safe_label(job_type), safe_label(status)).inc()


def observe_async_job_duration(job_type: str, duration_seconds: float) -> None:
    ASYNC_JOB_DURATION.labels(safe_label(job_type)).observe(max(duration_seconds, 0.0))


def inc_async_job_in_progress(job_type: str) -> None:
    ASYNC_JOBS_IN_PROGRESS.labels(safe_label(job_type)).inc()


def dec_async_job_in_progress(job_type: str) -> None:
    ASYNC_JOBS_IN_PROGRESS.labels(safe_label(job_type)).dec()


def record_llm_usage_metrics(
    *,
    provider: str,
    model: str,
    feature: str,
    status: str,
    prompt_tokens: int,
    completion_tokens: int,
    estimated_cost: Decimal,
    currency: str,
    latency_ms: int | None,
) -> None:
    labels = (safe_label(provider), safe_label(model), safe_label(feature), safe_label(status))
    LLM_CALLS.labels(*labels).inc()
    LLM_TOKENS.labels(labels[0], labels[1], labels[2], "prompt").inc(max(prompt_tokens, 0))
    LLM_TOKENS.labels(labels[0], labels[1], labels[2], "completion").inc(max(completion_tokens, 0))
    LLM_TOKENS.labels(labels[0], labels[1], labels[2], "total").inc(max(prompt_tokens, 0) + max(completion_tokens, 0))
    LLM_ESTIMATED_COST.labels(labels[0], labels[1], labels[2], safe_label(currency, "usd")).inc(max(float(estimated_cost), 0.0))
    if latency_ms is not None:
        LLM_LATENCY.labels(labels[0], labels[1], labels[2]).observe(max(latency_ms, 0) / 1000)


def set_dependency_ready(dependency: str, ready: bool) -> None:
    DEPENDENCY_READY.labels(safe_label(dependency)).set(1 if ready else 0)


def metrics_content() -> bytes:
    return generate_latest(REGISTRY)
