from __future__ import annotations


QUESTION_STATUS_DRAFT = "draft"
QUESTION_STATUS_PUBLISHED = "published"
QUESTION_STATUS_ACTIVE_LEGACY = "active"
QUESTION_STATUS_ARCHIVED = "archived"

PUBLISHED_QUESTION_STATUSES = {QUESTION_STATUS_ACTIVE_LEGACY, QUESTION_STATUS_PUBLISHED}
QUESTION_BANK_STATUSES = {
    QUESTION_STATUS_DRAFT,
    QUESTION_STATUS_PUBLISHED,
    QUESTION_STATUS_ACTIVE_LEGACY,
    QUESTION_STATUS_ARCHIVED,
}
